name: vpn_test
description: "Vpn UI Application"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen_runner: ^5.7.0
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.12

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/sfprodisplay/SF-Pro-Display-Black.otf
          weight: 900
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/static/Jost-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/jost/static/Jost-Light.ttf
          weight: 300
        - asset: assets/fonts/jost/static/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/jost/static/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/jost/static/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/jost/static/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/jost/static/Jost-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/jost/static/Jost-Black.ttf
          weight: 900

